Update manifiesto
Cloud-Native-Asturias/Sustainable-STEAM-driven-Development-of-Regions-Manifesto pull request #2
Opened 2023-01-19 23:51 UTC by Titogelo

See how the new items relate to the old ones:
- 1: to the old 1
- 2: to the old 10, 3, 2. Socio-emotional skills and 4C communication, critical thinking, collaboration and creativitiy are by-products of STEAM.
- 3: to the old 6, 7, 
- 4: to the old 11, and adds the gender discussion which was missing.
- 5: to the old 4.
- 6: I think we need this but it might go against the values `people and relationships over goals and objectives`

2023-01-22 19:04 UTC, marcosflobo requested changes

2023-01-22 19:04 UTC, marcosflobo commented on README.md
> -1. All initiatives are driven by transparency, honesty, and respect people.
- [ ] I like this one, I see it really important in the current era, with so much noise, and people fighting each other. I would propose keeping it.

2023-01-22 19:04 UTC, marcosflobo commented on README.md
> -1. Exchange among people and cultures must be encouraged.
- [ ] I like this one as well. I see important the point about exchanging with other parts of the world

2023-01-22 19:04 UTC, marcosflobo commented on README.md
> -1. Continuous improvement should be advocated at any time based on feedback.
- [ ] This one as well I like. Why? I think one of the mistakes that many organizations have is the lack of retrospectives and feedback, to be sure their strategy is continuously adapted (an organization is a living being!)

2023-02-08 17:28 UTC, marcosflobo approved these changes

2023-02-08 17:28 UTC, marcosflobo commented on README.md
> +2. Promote socio-emotional skills and 4 c's of learning 21st century essential for the development of a region.
```suggestion
2. Promote socio-emotional skills and Critical Thinking, Communication, Collaboration, and Creativity of learning 21st century essential for the development of a region.
```

2023-02-08 17:29 UTC, cloudnativeasturias approved these changes

2023-02-08 17:31 UTC, merged